services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: ssh
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pavl"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ssh
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:5000"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  pgdata:
